# NOTE: update this with your service name
service: blag-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-1:*:*"
  environment:
    blagTableName: blagPosts
    emailTableName: blagEmailReqs
    # auth info for post requests to be loaded from .env

resources:
  - ${file(resources/api-gateway-errors.yml)}

functions:
  newMessage:
    handler: handlers/newMessage.main
    events:
      - http:
          path: newMessage
          method: post
          cors: true

  getTitles:
    handler: handlers/getLatestTitles.main
    events:
      - http:
          path: titles
          method: get
          cors: true

  # no cors
  updatePortfolio:
    handler: handlers/updatePortfolio.main
    events:
      - http:
          path: updatePortfolio
          method: put

  # no cors
  newBlogPost:
    handler: handlers/newBlogPost.main
    events:
      - http:
          path: newBlogPost
          method: post

  hello:
    handler: handlers/hello.main
    events:
      - http:
          path: hello
          method: get
